version: '3.7'


services:
  pytest-py38:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.py38
    image: appsurify-testbrain-contrib:pytest-py38
    container_name: pytest-py38
    command: poetry run pytest
    volumes:
      - ./:/app/data

  pytest-py39:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.py39
    image: appsurify-testbrain-contrib:pytest-py39
    container_name: pytest-py39
    command: poetry run pytest
    volumes:
      - ./:/app/data

  pytest-py310:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.py310
    image: appsurify-testbrain-contrib:pytest-py310
    container_name: pytest-py310
    command: poetry run pytest
    volumes:
      - ./:/app/data

  pytest-py311:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.py311
    image: appsurify-testbrain-contrib:pytest-py311
    container_name: pytest-py311
    command: poetry run pytest
    volumes:
      - ./:/app/data

  pytest-py312:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.py312
    image: appsurify-testbrain-contrib:pytest-py312
    container_name: pytest-py312
    command: poetry run pytest
    volumes:
      - ./:/app/data


