name: "Qodana"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "development"
  push:
    branches:
      - "main"
      - "development"

jobs:
  analyze:
    name: "Analyze"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: "Checkout git"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: --baseline,qodana.sarif.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
