name: "Release publish"

on:
  release:
    types: [released]

jobs:
  pypi-publish:
    name: "PyPi Publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.1"
      - name: "Download built artifacts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download -D dist/ ${{ github.event.release.name }}
      - name: "Upload to PyPI"
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
