name: "Testbrain Webhook"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "releases/*.*.*"
      - "!development"
      - "!testing"

jobs:
  delivery:
    name: "Delivery to TB server"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: "Setup testbrain cli"
        run: |
          pip3 install appsurify-testbrain-cli
      - name: "Push changes to the server"
        run: |
          testbrain repository git push \
          --repo-dir ${{ github.workspace }} \
          --server ${{ vars.TESTBRAIN_SERVER }} \
          --token ${{ secrets.TESTBRAIN_TOKEN }} \
          --project ${{ vars.TESTBRAIN_PROJECT }} \
          --branch ${{ github.ref_name }} \
          --commit ${{ github.sha }} \
          --number ${{ vars.TESTBRAIN_NUMBER_OF_COMMITS }} \
          --loglevel INFO
      - name: "Upload crashdumps"
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: testbrain-repository-crashdump
          path: .crashdumps/
          retention-days: 3
