name: "Testbrain"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "releases/*.*.*"

jobs:
  delivery:
    name: "Delivery"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout git"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: "Set up Testbrain CLI"
        run: |
          pip3 install appsurify-testbrain-cli
      - name: "Delivering changes to the server"
        run: |
          testbrain repository git push \
          --repo-dir ${{ github.workspace }} \
          --server ${{ vars.TESTBRAIN_SERVER }} \
          --token ${{ secrets.TESTBRAIN_TOKEN }} \
          --project ${{ vars.TESTBRAIN_PROJECT }} \
          --branch ${{ github.ref_name }} \
          --commit ${{ github.sha }} \
          --number ${{ vars.TESTBRAIN_NUMBER_OF_COMMITS }} \
          --loglevel INFO
      - name: "Upload crash dumps"
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: "crashdumps"
          path: ${{ github.workspace }}/.crashdumps/
          retention-days: 1
